
- name: Instll MySQL 5.7 repo
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
    state: present

- name: Import GPG key for MySQL 5.7
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-community-server
    - mysql-community-client
    - MySQL-python

- name: Start MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Change mysql root password and keep track in 
  shell: |
    password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
    echo $password_match
    mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '4ok6-O4<fL>6a'; flush privileges; "
    echo "[client]
    user=root
    password=4ok6-O4<fL>6a" > /root/.my.cnf
  register: change_temp_pass

# display output in the console
- debug: var=change_temp_pass.stdout_lines

- name: Restart MySQL service
  service:
    name: mysqld
    state: restarted
    enabled: true

- name: Create application database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create database user
  mysql_user:
    name: "{{ db_user }}"
    password:  "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
    